#!/bin/bash

VCS="github"
CIRCLE_PROJECT_USERNAME="brianoh1979"

base64 --decode encoded-envvar2.csv > envvar2.csv
while IFS=, read name value1 value2
do

echo $name
echo $value1
echo $value2

circleci context create $VCS $CIRCLE_PROJECT_USERNAME $name
circleci context show $VCS $CIRCLE_PROJECT_USERNAME $name
echo $value2 | \
circleci context store-secret $VCS $CIRCLE_PROJECT_USERNAME $name $value1
circleci context show $VCS $CIRCLE_PROJECT_USERNAME $name

done < envvar2.csv

#echo "Charlie" | \
#circleci context store-secret $VCS $CIRCLE_PROJECT_USERNAME ALICE BRIAN
#circleci context show $VCS $CIRCLE_PROJECT_USERNAME ALICE
